apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-oss5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-oss5
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-oss5
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-oss5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-oss5
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mwrz-tenant/nodejs-users/simple-nodejs-app-oss5@sha256:3ebb8be623a25ef79334ac761373b762817f9a65e4f2c8c22c63b4cd0ea21e19
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
