apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: simple-nodejs-app-oss5
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mwrz-tenant/nodejs-users/simple-nodejs-app-oss5@sha256:3ebb8be623a25ef79334ac761373b762817f9a65e4f2c8c22c63b4cd0ea21e19
        name: my-nodejs
        resources: {}
status: {}
